### ISSUE TITLE
Verdant Sprigs/Infernal Stems do not drop on right-click

### ISSUE THREAD

**Issue by F4ndroid** [elucent/Roots#26]
Dunno if this is an issue with this mod or EnderCore/Pam's, but yeah.

**Comment by elucent** [comment]
It's debatably an issue with either of us. My items drop when a block is harvested, so depending on your right-click harvest mod, they could drop or they might not, depending on whether onBlockHarvested is called. EnderCore alone will work, but I think Pam's overrides that and stops it from working.

I can imagine three options: either I add specific compatibility checking to every right-click harvest mod out there and change my events, right-click harvest mods add compatibility with me, or I just leave it as-is and you have the option of breaking plants to actually get drops from them. 

I'll close this issue for now since adding specific compat to every harvest mod out there is kind of impractical, and I think there might be a way around it. I'll do some research into Forge events, and if I can figure out a good way to fix this, I'll respond here and include the changes in a future release.
