### ISSUE TITLE
Tall grass varieties from Biomes O' Plenty never drop Old Roots

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#29]
Maybe I'm just super unlucky, but I've never, EVER seen an Old Root drop from the BOP tall grass variants. I've gotten a few from NORMAL tall grass(as in, the grass from vanilla Minecraft), but I've only ever gotten seeds from the BOP grass - nothing else. I'm pretty sure BOP grass is supposed to drop anything that's in a specific kind of "tall grass" drop pool of some sort, but I'm not entirely sure how it works, so... take from that what you will.

Just thought I'd bring it up is all. Sorry for the influx of issues I've posted... heh.

**Comment by elucent** [comment]
No, it's great! These issues have to be fixed. For this one, however, I don't think there's much I can do. BoP hardcodes its item drops and doesn't depend on a tall grass loot table, so it won't return the old roots. 
I could, however, add a config option that allows you to modify the chances so that in your instance there's a 1/10 chance when breaking vanilla tall grass. That should make them more attainable.
