### ISSUE TITLE
Suggestion: New modifier type, "Charge"

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#38]
I often find myself not using the spells as much as I could be because it takes so long to charge them up in the thick of combat and their range is so limited. I find it rather ineffective to use them to fight mobs even though so many of the effects from different flowers are made for attacking/damaging mobs. I propose a fourth modifier, "Charge", which would decrease the time a spell takes to activate/charge per modifier used, and would be made by using blaze powder as a modifier ingredient.

Just a thought.

**Comment by Febilian** [comment]
I realized blaze powder may be a component for other spell parts, so you could alternatively wrap this into the same material as efficiency with redstone perhaps? Or another ingredient which isn't used in something else.

**Comment by elucent** [comment]
The slow charging is somewhat intentional. This mod essentially allows you to get a diamond sword on the first night if you play your cards right, so in order to balance that, spells must be used very strategically. If you have good cover, like in a forest or cave, you might want to try casting around corners, or keeping a tree between you and the target at all times so they can't quite hit you.

Staffs also aren't intended to just be your single go-to combat solution, at least not yet. Having a sword in one hand and a staff in the other is a pretty effective combo I find, I typically start combat by getting as many shots in as possible with a rose's thorns staff and then use the sword to either finish the job or knock the enemy further away.

Still, I don't see any reason why making this configurable would be a bad idea.

I am actually planning on adding another casting item intended for combat, with a drastically reduced charging time, but the position of that in the progression means that I have a lot of work to do before I can make it.

**Comment by Febilian** [comment]
I'm new to 1.9 and I completely forgot that the offhand slot is a thing. I feel rather silly now!
