### ISSUE TITLE
Staffs ignore PVP settings

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#43]
If it hadn't been with a good friend who had the means to fight back with another staff and gamerule keepInventory=true... there might have been some more anger about it.

Staffs seem to affect other players, even if PVP is turned off. I was using dandelion's winds to throw them in the air, and they were straight up just using the rose's thorns staff on me to do direct damage.

**Comment by elucent** [comment]
That's an oversight on my part, sorry about it. I'll add a checker.

**Comment by elucent** [comment]
Just fixed! One caveat: the spells for the Flare Orchid and the Poisonous Potato, since they use generic explosions and lightning bolts, could still be used for PvP. I'd rather not change them to just not work when players are around, so just use them responsibly. The same could be done with PSI or several other mods, so I figure it's okay.
