### ISSUE TITLE
(Suggestion)  Wildwood armor needs a little balancing

### ISSUE THREAD

**Issue by doctorkreger** [elucent/Roots#52]
As it stands, its perhaps a little to good for its costs.  Since equipping it, I barely worry about any size group of enemies, and since it heals itself I'll never have a reason to unequip or do the ritual again.

Maybe lower the self repair rate? Cut its total durability to a much lower level, forcing you to use it to shorter bursts or risk breaking? Or, maybe most simply, lower the awesome armor value, as the regen on top of armor without toughness would still be amazing.

**Comment by elucent** [comment]
I think I'm going to ditch the increased regen mechanic. It's a bit of a headache, since people have been using it to cheat through Blood Magic and it makes the armor quite powerful. I think having a simple armor set with a decent protection value plus toughness and self-repair is good enough.

I will revisit increased regen later, in another progression stage of the mod.
