### ISSUE TITLE
Wildwood armor set no longer gives regen

### ISSUE THREAD

**Issue by LordHellscream** [elucent/Roots#77]
I just noticed the set of wildwood armor i made a few versions back no longer gives regen. I am wearing full set. The armor are enchanted with some various enchantments (defense, mending, unbreaking etc etc).

Version I am using is 1.9.4.0.110.0

**Comment by elucent** [comment]
That is intentional, though I believe I forgot to update the tablet entry. The free regen of the wildwood armor was proving to be a bit unbalanced regarding other mods (read: Blood Magic), at least in the early game. I have plans to reintroduce such a feature in a future update, but we have some other, very interesting features that we plan to release first.

Stay tuned!
