### ISSUE TITLE
[Mod Integration] JEI Support 

### ISSUE THREAD

**Issue by Dijkstra1** [elucent/Roots#85]
In the ~~book~~ runic tablet, it not always easy to tell, what is required, or if ore substitutes can be used, JEI Support what nice, and if you could mouse items in the book and get their name, and it have it cycle ore substitutes.

**Comment by elucent** [comment]
That's not exactly JEI Support, just Ore Dictionary support. In our code, we aren't assigning certain Ore Dictionary keys to our recipes; rather, if the item you use matches an oredict with the item the recipe wants, it'll still get accepted.

I could potentially add Ore Dictionary support to tooltips though.

**Comment by Dijkstra1** [comment]
If you can make, say the item/ore name when mouse in the book, I could live with that, be able to look recipes fro staffs in JEI would be better, I thought you could make a JEI plugin and then embed in your book, thus letting me see items by mousing and showing all ore substitutes, but good mod, I like something that is different.

**Comment by elucent** [comment]
The ore substitutes might be a little tricky since there are no recipes that have ore dictionary keys defined in them. As long as the item you're using has at least one oredict key in common with the recipe item, it should work.

We could potentially add a JEI plugin, but I'd rather have more control over how people view our information. It also might not work well, since all the staves and the petal dusts are the same item and are registered as such.

**Comment by Dijkstra1** [comment]
I think you can NBT variants into JEI well I know it has been done with NEI in the past, I understand you want for control, I hate using external libs my self, and have JEI in book would change it visual appearance. The reason, want to show ores, is I do not know if I see red mushroom, in the book weather I can use brown mushrooms or even, white mushrooms for pams's harvest craft, and one recipe seems to want red sand, and I would hate to find that could have use sand instead after getting red sand for it.

**Comment by ShadowGamerXY** [comment]
If you are thinking of us making the JEI compat, so you will see all the recipes in JEI, well it is not that hard to do, but I do not really see the point because: 1.We don't have a an recipe that is really long and has a lot of steps to it, 99% of the recipes, require less than 6 components, and for example in spell crafting all of the base components and modifiers remain the same, eventually we may make a JEI compat but as it is for now, we are focusing on the polishing, bug fixing and making the mod bigger with content and not integration with "helper" mods like JEI, that will come later when the mod is bigger and has a lot of different custom recipes and recipe mechanics. So if elucent has no more to say I will close this thread for now.
